@startuml cdYouTubeDownloaderSWComponents.svg
skinparam titleFontSize 30
skinparam titleFontStyle bold
skinparam packageBorderColor black
skinparam packageFontSize 18
skinparam groupFontStyle bold
skinparam componentBorderColor black
skinparam interfaceBorderColor black
skinparam CollectionsBorderColor black

title SW components of YouTubeDownloader Tool

node "app.ico" as icon #yellow

package "YouTubeDownloader" as YtDl #ededed {
  component "**app**" as app #63d8ff
  note left of app
    Application entry point:
    Init and startup
  end note
  package "Controller" as controller {
    [main_window]
  }
  package "Util" as util {
    [app_data] as data
  }
  note top of data
    Constants (e.g paths, keys) and
    Functions related to data.
    Included by most components.
  end note
  package "Worker" {
    [downloader]
  }
  [app] -d-> [main_window]
  [app] -[#black]u--> icon
}

node "YouTubeDownloader.exe" #plum

package "Python Libraries (mostly third party)" #lightgreen {
 [PyInstaller]
 [pytube]
}

[app] -[#black]-> [downloader]
[downloader] -[#black]-> [pytube]
[PyInstaller] -[#black]d-> YouTubeDownloader.exe
@enduml
