labels:
  - name: Bug
    description: Typ: Fehler
    color: #ff0000
  - name: Feature
    description: Typ: Neues Feature
    color: #69d100
  - name: Improvement
    description: Typ: Optimierungen
    color: #9400d3
  - name: In Progress
    description: Status: Issue ist in Bearbeitung (Entwicklung)
    color: #69d100
  - name: In Review
    description: Status: Issue ist in Bearbeitung (Review)
    color: #00b140
  - name: BLOCKER
    description: Priorität: höher als HIGH. Blockiert die Weiterentwicklung.
    color: #ff0000
  - name: HIGH
    description: Priorität: Hoch
    color: #ff0000
  - name: MEDIUM
    description: Priorität: Mittel
    color: #f0ad4e
  - name: LOW
    description: Priorität: Niedrig
    color: #5cb85c
  - name: BLOCKIERT
    description: An Issue kann nicht weiter gearbeitet werden.
    color: #d1d100
  - name: Diskussion
    description: Einordnung des Issues muss noch geklärt werden.
    color: #8e44ad
  - name: HW
    description: Hardware Issue
    color: #0000ff
  - name: SW
    description: Software Issue
    color: #3cb371
  - name: Doku
    description: Dokumentations Issue
    color: #34495e
