name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["Bug"]
projects: []
assignees:
  - timounger
body:
  - type: markdown
    attributes:
      value: |
        Details zum Fehlerbericht eingeben!
