name: Bug Report
description: Einen Fehlerbericht einreichen
title: "[Bug]: "
labels: ["Bug"]
projects: []
assignees:
  - timounger
body:
  - type: markdown
    attributes:
      value: |
        Details zum Fehlerbericht eingeben!
  - type: input
    id: contact
    attributes:
      label: Kontaktangaben
      description: Wie können wir mit Ihnen in Kontakt treten, wenn wir mehr Informationen benötigen?
      placeholder: z.B. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Was ist geschehen?
      description: Beschreiben Sie welcher Fehler aufgetreten ist.
      placeholder: Sagen Sie uns, was passiert ist!
      value: "Ein Fehler ist aufgetreten!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Welche Version der BonPrinter Software verwenden Sie?
      placeholder: "vX.X.X  (Git SHA: XXXXXXXX)"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Gibt es eine Lösungsmöglichkeit?
      description: Beschreiben Sie wie eine Lösung aussehen könnte.
      placeholder: Sagen Sie uns, wie ien Lösungsmöglichkeit aussehen kann!
      value: "Das Problem kann wie folgt gelöst werden:"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevante Log-Ausgaben
      description: Bitte kopieren Sie alle relevanten Protokollausgaben und fügen Sie sie ein.
      render: python
