name: Feature request
description: Eine Projektidee vorschlagen
title: "[Feat] "
labels: ["Feature"]
projects: []
assignees:
  - timounger
body:
  - type: markdown
    attributes:
      value: Details zur Projektidee eingeben!
  - type: textarea
    id: functionality
    attributes:
      label: Was ist Ihr Vorschlag?
      description: Beschreiben Sie die Akzeptanzkriterien f端r die Umsetzung Ihrer Idee.
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Welche Aufgaben sind zu erf端llen?
      description: Beschreiben Sie die Aufgaben, die zur Umsetzung Ihrer Idee durchgef端hrt werden m端ssen.
    validations:
      required: false
