---
name: Bug Report
about: Erstelle einen Bericht, um uns bei der Fehlerbehebung zu unterstützen
title: '[BUG]'
labels: bug
assignees: ''

---

**Beschreibe den Fehler**
Eine klare und prägnante Beschreibung des Fehlers.

**Schritte zum Reproduzieren**
Schritte, um den Fehler zu reproduzieren:
1. Gehe zu '...'
2. Klicke auf '....'
3. Scrolle nach unten zu '....'
4. Fehler tritt auf

**Erwartetes Verhalten**
Eine klare und prägnante Beschreibung dessen, was du erwartet hast.

**Screenshots**
Wenn möglich, füge Screenshots hinzu, um den Fehler zu erklären.

**Desktop (bitte fülle die folgenden Informationen aus):**
- Betriebssystem: [z. B. Windows, macOS]
- Browser [z. B. Chrome, Safari]

**Smartphone (bitte fülle die folgenden Informationen aus):**
- Gerät: [z. B. iPhone6]
- Betriebssystem: [z. B. iOS8.1]
- Browser [z. B. Standardbrowser, Safari]

**Zusätzliche Informationen**
Füge hier weitere Informationen über den Fehler hinzu, falls erforderlich.

**Optional: Vorschläge zur Behebung**
Falls du Vorschläge zur Behebung des Fehlers hast, teile sie bitte mit.

---

**Auswahlfeld 1**
- [ ] Option 1
- [ ] Option 2
- [ ] Option 3

**Auswahlfeld 2**
- [ ] Option A
- [ ] Option B
- [ ] Option C
