---
#------------------------------------------------------------------------------
# Central YouTubeDownloader GitHub CI
# Doc: https://docs.github.com/de/actions
#------------------------------------------------------------------------------
name: YouTubeDownloader CI

#------------------------------------------------------------------------------
# Token Permission
#------------------------------------------------------------------------------
permissions:
  actions: write
  checks: none
  contents: write
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: write
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

defaults:
  run:
    shell: cmd

env:
  PYTHON_VERSION: 3.11.9
  PYTHON_ARCH: x64
  PYTHON_PACKAGE_INST_PATH: ./Documentation/Installation
  PYTHON_PACKAGE_INST_FILE: install_packages.bat
  DOXYGEN_OUTPUT_NAME: Output_Doxygen
  DOXYGEN_OUTPUT_PATH: ./Documentation/DoxygenCreator/Output_Doxygen
  BINARY_EXE_NAME: bin_Exe
  BINARY_SETUP_NAME: bin_Setup
  BINARY_PATH: ./Executable/bin

#--------------------------------------------------------------------------------
# WORKFLOW TRIGGER
#--------------------------------------------------------------------------------
on:
  push:
    branches:
      - master
    #paths:
      #- "Source/version.py"
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      documentation:
        description: "Documentation"
        type: choice
        default: check
        options:
          - none
          - check
          - publish
          - clean publish
      test:
        description: "Test"
        type: choice
        default: static
        options:
          - none
          - static
      build:
        description: "Build"
        type: choice
        default: setup
        options:
          - none
          - exe
          - setup
      create_release:
        description: "Create Release. All jobs are executed."
        type: boolean
        default: false

#--------------------------------------------------------------------------------
# WORKFLOW JOBS
#--------------------------------------------------------------------------------
jobs:
  doc-Doxygen:
    if: (inputs.documentation != 'none') || inputs.create_release || (github.event_name == 'push')
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: ${{ env.PYTHON_ARCH }}
      - name: Install Graphviz
        run: choco install graphviz
      - name: Install Packages
        working-directory: ${{ env.PYTHON_PACKAGE_INST_PATH }}
        run: ${{ env.PYTHON_PACKAGE_INST_FILE }}
      - name: Run Doxygen
        working-directory: ./Documentation/DoxygenCreator
        run: ..\..\.venv\Scripts\python create_doxygen.py
      - name: Upload Doxygen Output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DOXYGEN_OUTPUT_NAME }}
          path: ${{ env.DOXYGEN_OUTPUT_PATH }}
  #------------------------------------------------------------------------------
  doc-Pages:
    if: (inputs.documentation == 'publish') || (inputs.documentation == 'clean publish') || inputs.create_release || (github.event_name == 'push')
    needs: doc-Doxygen
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Doxygen Output
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.DOXYGEN_OUTPUT_NAME }}
          path: ${{ env.DOXYGEN_OUTPUT_PATH }}
      - name: Delete gh-pages branch
        if: inputs.documentation == 'clean publish'
        run: |
          git checkout gh-pages
          git push origin --delete gh-pages
      - name: Set up Python
        if: github.event_name == 'push'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: ${{ env.PYTHON_ARCH }}
      - name: Get prerelease status
        if: github.event_name == 'push'
        shell: powershell
        run: |
          $version = $(python -c "from Source.version import PRERELEASE_BUILD; print(PRERELEASE_BUILD)")
          echo "prerelease_version=$version" >> $env:GITHUB_ENV
      - name: Deploy to Github Pages
        if: (github.event_name != 'push') || (env.prerelease_version == 'false')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.DOXYGEN_OUTPUT_PATH }}/html
  #------------------------------------------------------------------------------
  test-PyLint:
    if: (inputs.test == 'static') || (inputs.build != 'none') || inputs.create_release || (github.event_name == 'push')
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: ${{ env.PYTHON_ARCH }}
      - name: Install Packages
        working-directory: ${{ env.PYTHON_PACKAGE_INST_PATH }}
        run: ${{ env.PYTHON_PACKAGE_INST_FILE }}
      - name: Run PyLint
        working-directory: ./Test
        run: run_pylint.bat
      - name: Upload PyLint report
        uses: actions/upload-artifact@v4
        with:
          name: pylint.log
          path: ./Test/pylint.log
  #------------------------------------------------------------------------------
  build-Exe:
    if: (inputs.build != 'none') || inputs.create_release || (github.event_name == 'push')
    needs: [test-PyLint]
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: ${{ env.PYTHON_ARCH }}
      - name: Install Packages
        working-directory: ${{ env.PYTHON_PACKAGE_INST_PATH }}
        run: ${{ env.PYTHON_PACKAGE_INST_FILE }}
      - name: Get Package list
        working-directory: ${{ env.PYTHON_PACKAGE_INST_PATH }}
        run: get_package_list.bat
      - name: Upload Package list
        uses: actions/upload-artifact@v4
        with:
          name: installed_packages.txt
          path: ./Documentation/Installation/installed_packages.txt
      - name: Build Executable
        working-directory: ./Executable
        run: generate_executable.bat
      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_EXE_NAME }}
          path: ${{ env.BINARY_PATH }}
  #------------------------------------------------------------------------------
  build-Setup:
    needs: build-Exe
    if: (inputs.build == 'setup') || inputs.create_release || (github.event_name == 'push')
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Executable
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_EXE_NAME }}
          path: ${{ env.BINARY_PATH }}
      - name: Build Setup
        working-directory: ./Executable
        run: generate_setup.bat
      - name: Delete Executable file
        run: |
          rm -f ${{ env.BINARY_PATH }}/YouTubeDownloader.exe
      - name: Upload Setup
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_SETUP_NAME }}
          path: ${{ env.BINARY_PATH }}
  #------------------------------------------------------------------------------
  create-Release:
    if: inputs.create_release || (github.event_name == 'push')
    needs: build-Setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Setup
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_SETUP_NAME }}
          path: ${{ env.BINARY_PATH }}
      - name: Get Commit Message
        shell: bash
        run: echo "commit_message=$(git log -1 --pretty=format:"%s")" >> $GITHUB_ENV
      - name: Get version from Python file
        shell: bash
        run: |
          version=$(python -c 'from Source.version import __version__; print(__version__)')
          echo "file_version=${version}" >> $GITHUB_ENV
      - name: Get prerelease status
        shell: bash
        run: |
          prerelease=$(python -c 'from Source.version import PRERELEASE_BUILD; print(PRERELEASE_BUILD)')
          echo "prerelease_version=${prerelease}" >> $GITHUB_ENV
      - name: Create tag
        if: (github.event_name != 'push') || (env.prerelease_version == 'false')
        shell: bash
        run: |
          tag_name="v${{ env.file_version }}"
          git tag "$tag_name"
          git push origin "$tag_name"
      - name: Create release
        if: (github.event_name != 'push') || (env.prerelease_version == 'false')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.file_version }}
          release_name: "[YouTubeDownloader] v${{ env.file_version }}"
          body: "Git SHA: ${{ github.sha }}\n\n${{ env.commit_message }}"
          draft: false
          prerelease: false
      - name: Upload Setup files to release assets
        if: (github.event_name != 'push') || (env.prerelease_version == 'false')
        shell: bash
        run: |
          for file in ${{ env.BINARY_PATH }}/*; do
            filename=$(basename "$file")
            curl -X POST "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets?name=$filename" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: $(file -b --mime-type $file)" \
              --data-binary @"$file"
          done
